# Generated by Django 4.1.7 on 2023-04-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('Idno', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
