# Generated by Django 4.1.7 on 2023-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='food',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
